name: SAT solver benchmark

on:
  pull_request:
    branches:
      - master

jobs:
  bench:
    runs-on: alpine-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test echo
        run: echo "IT must be echoed for all branches except master!!!"
